#docker-compose for development purposes only
#You should only ever use this if you are documenting the API,
#Or if you are modifying this service

#In subjectDaoServiceFolder run with docker-compose -f dev-docker-compose.yml up

version: '3.7'

services:
  dev-app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - "DB_CONNECTION_STRING=sqlite:///dev-db.sqlite3"
