#See the postgres Docker Documentation here:
#https://hub.docker.com/_/postgres

#
version: '3.7'

services:
  web:
#    working_dir: .
    build: .
    container_name: patientDaoService
    ports:
      - 9001:5000
networks:
  default:
    external:
      name: femrdb_femrNetDb