#
#  patient_service_dao:
##    networks:
##      - daoToDbNet
#    build:  #future: images: femr/#    ports:
#      - 9001:5000
#    environment:
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=test
#      - PGDATA=/var/lib/postgresql/data
#    depends_on:
#      - femrdb
#    links:
#      - femrdb
##networks:
##  daoToDbNet: