version: '3.7'

services:
  femrdb:
#    networks:
#      - daoToDbNet
    image: postgres:12
    ports:
      - 5432:5432
  patient_service_dao:
#    networks:
#      - daoToDbNet
    build: daoServices/patientDaoService #future: images: femr/patientDaoService
    ports:
      - 9001:5000
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
      - PGDATA=/var/lib/postgresql/data
    depends_on:
      - femrdb
    links:
      - femrdb
#networks:
#  daoToDbNet: