/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetItemSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetItemSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetItemSchema
        //private GetItemSchema instance;

        public GetItemSchemaTests()
        {
            // TODO uncomment below to create an instance of GetItemSchema
            //instance = new GetItemSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetItemSchema
        /// </summary>
        [Fact]
        public void GetItemSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetItemSchema
            //Assert.IsInstanceOfType<GetItemSchema> (instance, "variable 'instance' is a GetItemSchema");
        }


        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Fact]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }
        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Fact]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }

    }

}
