/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetInfoSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetInfoSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetInfoSchema
        //private GetInfoSchema instance;

        public GetInfoSchemaTests()
        {
            // TODO uncomment below to create an instance of GetInfoSchema
            //instance = new GetInfoSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetInfoSchema
        /// </summary>
        [Fact]
        public void GetInfoSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetInfoSchema
            //Assert.IsInstanceOfType<GetInfoSchema> (instance, "variable 'instance' is a GetInfoSchema");
        }


        /// <summary>
        /// Test the property 'AddColumns'
        /// </summary>
        [Fact]
        public void AddColumnsTest()
        {
            // TODO unit test for the property 'AddColumns'
        }
        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Fact]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }

    }

}
