/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetInfoSchemaAddColumns
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetInfoSchemaAddColumnsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetInfoSchemaAddColumns
        //private GetInfoSchemaAddColumns instance;

        public GetInfoSchemaAddColumnsTests()
        {
            // TODO uncomment below to create an instance of GetInfoSchemaAddColumns
            //instance = new GetInfoSchemaAddColumns();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetInfoSchemaAddColumns
        /// </summary>
        [Fact]
        public void GetInfoSchemaAddColumnsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetInfoSchemaAddColumns
            //Assert.IsInstanceOfType<GetInfoSchemaAddColumns> (instance, "variable 'instance' is a GetInfoSchemaAddColumns");
        }


        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

    }

}
