/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetListSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetListSchemaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetListSchema
        //private GetListSchema instance;

        public GetListSchemaTests()
        {
            // TODO uncomment below to create an instance of GetListSchema
            //instance = new GetListSchema();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetListSchema
        /// </summary>
        [Fact]
        public void GetListSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetListSchema
            //Assert.IsInstanceOfType<GetListSchema> (instance, "variable 'instance' is a GetListSchema");
        }


        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Fact]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }
        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Fact]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }
        /// <summary>
        /// Test the property 'OrderColumn'
        /// </summary>
        [Fact]
        public void OrderColumnTest()
        {
            // TODO unit test for the property 'OrderColumn'
        }
        /// <summary>
        /// Test the property 'OrderDirection'
        /// </summary>
        [Fact]
        public void OrderDirectionTest()
        {
            // TODO unit test for the property 'OrderDirection'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

    }

}
