/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing GetListSchemaFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetListSchemaFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetListSchemaFilters
        //private GetListSchemaFilters instance;

        public GetListSchemaFiltersTests()
        {
            // TODO uncomment below to create an instance of GetListSchemaFilters
            //instance = new GetListSchemaFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetListSchemaFilters
        /// </summary>
        [Fact]
        public void GetListSchemaFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetListSchemaFilters
            //Assert.IsInstanceOfType<GetListSchemaFilters> (instance, "variable 'instance' is a GetListSchemaFilters");
        }


        /// <summary>
        /// Test the property 'Col'
        /// </summary>
        [Fact]
        public void ColTest()
        {
            // TODO unit test for the property 'Col'
        }
        /// <summary>
        /// Test the property 'Opr'
        /// </summary>
        [Fact]
        public void OprTest()
        {
            // TODO unit test for the property 'Opr'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
