/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2003
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2003Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2003
        //private InlineResponse2003 instance;

        public InlineResponse2003Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2003
            //instance = new InlineResponse2003();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2003
        /// </summary>
        [Fact]
        public void InlineResponse2003InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2003
            //Assert.IsInstanceOfType<InlineResponse2003> (instance, "variable 'instance' is a InlineResponse2003");
        }


        /// <summary>
        /// Test the property 'AddColumns'
        /// </summary>
        [Fact]
        public void AddColumnsTest()
        {
            // TODO unit test for the property 'AddColumns'
        }
        /// <summary>
        /// Test the property 'EditColumns'
        /// </summary>
        [Fact]
        public void EditColumnsTest()
        {
            // TODO unit test for the property 'EditColumns'
        }
        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Fact]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }

    }

}
