/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2006
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2006Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2006
        //private InlineResponse2006 instance;

        public InlineResponse2006Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2006
            //instance = new InlineResponse2006();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2006
        /// </summary>
        [Fact]
        public void InlineResponse2006InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2006
            //Assert.IsInstanceOfType<InlineResponse2006> (instance, "variable 'instance' is a InlineResponse2006");
        }


        /// <summary>
        /// Test the property 'DescriptionColumns'
        /// </summary>
        [Fact]
        public void DescriptionColumnsTest()
        {
            // TODO unit test for the property 'DescriptionColumns'
        }
        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Fact]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
        /// <summary>
        /// Test the property 'LabelColumns'
        /// </summary>
        [Fact]
        public void LabelColumnsTest()
        {
            // TODO unit test for the property 'LabelColumns'
        }
        /// <summary>
        /// Test the property 'ListColumns'
        /// </summary>
        [Fact]
        public void ListColumnsTest()
        {
            // TODO unit test for the property 'ListColumns'
        }
        /// <summary>
        /// Test the property 'ListTitle'
        /// </summary>
        [Fact]
        public void ListTitleTest()
        {
            // TODO unit test for the property 'ListTitle'
        }
        /// <summary>
        /// Test the property 'OrderColumns'
        /// </summary>
        [Fact]
        public void OrderColumnsTest()
        {
            // TODO unit test for the property 'OrderColumns'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
