/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2005
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2005Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2005
        //private InlineResponse2005 instance;

        public InlineResponse2005Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2005
            //instance = new InlineResponse2005();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2005
        /// </summary>
        [Fact]
        public void InlineResponse2005InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2005
            //Assert.IsInstanceOfType<InlineResponse2005> (instance, "variable 'instance' is a InlineResponse2005");
        }


        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }

    }

}
