/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse404
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse404Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse404
        //private InlineResponse404 instance;

        public InlineResponse404Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse404
            //instance = new InlineResponse404();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse404
        /// </summary>
        [Fact]
        public void InlineResponse404InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse404
            //Assert.IsInstanceOfType<InlineResponse404> (instance, "variable 'instance' is a InlineResponse404");
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
