/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineResponse2007
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineResponse2007Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineResponse2007
        //private InlineResponse2007 instance;

        public InlineResponse2007Tests()
        {
            // TODO uncomment below to create an instance of InlineResponse2007
            //instance = new InlineResponse2007();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineResponse2007
        /// </summary>
        [Fact]
        public void InlineResponse2007InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse2007
            //Assert.IsInstanceOfType<InlineResponse2007> (instance, "variable 'instance' is a InlineResponse2007");
        }


        /// <summary>
        /// Test the property 'DescriptionColumns'
        /// </summary>
        [Fact]
        public void DescriptionColumnsTest()
        {
            // TODO unit test for the property 'DescriptionColumns'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LabelColumns'
        /// </summary>
        [Fact]
        public void LabelColumnsTest()
        {
            // TODO unit test for the property 'LabelColumns'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'ShowColumns'
        /// </summary>
        [Fact]
        public void ShowColumnsTest()
        {
            // TODO unit test for the property 'ShowColumns'
        }
        /// <summary>
        /// Test the property 'ShowTitle'
        /// </summary>
        [Fact]
        public void ShowTitleTest()
        {
            // TODO unit test for the property 'ShowTitle'
        }

    }

}
