/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing InlineObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject
        //private InlineObject instance;

        public InlineObjectTests()
        {
            // TODO uncomment below to create an instance of InlineObject
            //instance = new InlineObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject
        /// </summary>
        [Fact]
        public void InlineObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineObject
            //Assert.IsInstanceOfType<InlineObject> (instance, "variable 'instance' is a InlineObject");
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Provider'
        /// </summary>
        [Fact]
        public void ProviderTest()
        {
            // TODO unit test for the property 'Provider'
        }
        /// <summary>
        /// Test the property 'Refresh'
        /// </summary>
        [Fact]
        public void RefreshTest()
        {
            // TODO unit test for the property 'Refresh'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
