/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SubjectInfoModelApiPost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubjectInfoModelApiPostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubjectInfoModelApiPost
        //private SubjectInfoModelApiPost instance;

        public SubjectInfoModelApiPostTests()
        {
            // TODO uncomment below to create an instance of SubjectInfoModelApiPost
            //instance = new SubjectInfoModelApiPost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubjectInfoModelApiPost
        /// </summary>
        [Fact]
        public void SubjectInfoModelApiPostInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubjectInfoModelApiPost
            //Assert.IsInstanceOfType<SubjectInfoModelApiPost> (instance, "variable 'instance' is a SubjectInfoModelApiPost");
        }


        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

    }

}
