/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SubjectModelApiGetList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubjectModelApiGetListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubjectModelApiGetList
        //private SubjectModelApiGetList instance;

        public SubjectModelApiGetListTests()
        {
            // TODO uncomment below to create an instance of SubjectModelApiGetList
            //instance = new SubjectModelApiGetList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubjectModelApiGetList
        /// </summary>
        [Fact]
        public void SubjectModelApiGetListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubjectModelApiGetList
            //Assert.IsInstanceOfType<SubjectModelApiGetList> (instance, "variable 'instance' is a SubjectModelApiGetList");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
