/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SubjectModelApiPost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubjectModelApiPostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubjectModelApiPost
        //private SubjectModelApiPost instance;

        public SubjectModelApiPostTests()
        {
            // TODO uncomment below to create an instance of SubjectModelApiPost
            //instance = new SubjectModelApiPost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubjectModelApiPost
        /// </summary>
        [Fact]
        public void SubjectModelApiPostInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubjectModelApiPost
            //Assert.IsInstanceOfType<SubjectModelApiPost> (instance, "variable 'instance' is a SubjectModelApiPost");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
