/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SubjectInfoModelApiPut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubjectInfoModelApiPutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubjectInfoModelApiPut
        //private SubjectInfoModelApiPut instance;

        public SubjectInfoModelApiPutTests()
        {
            // TODO uncomment below to create an instance of SubjectInfoModelApiPut
            //instance = new SubjectInfoModelApiPut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubjectInfoModelApiPut
        /// </summary>
        [Fact]
        public void SubjectInfoModelApiPutInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubjectInfoModelApiPut
            //Assert.IsInstanceOfType<SubjectInfoModelApiPut> (instance, "variable 'instance' is a SubjectInfoModelApiPut");
        }


        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Fact]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

    }

}
