/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing SubjectModelApiGet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubjectModelApiGetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubjectModelApiGet
        //private SubjectModelApiGet instance;

        public SubjectModelApiGetTests()
        {
            // TODO uncomment below to create an instance of SubjectModelApiGet
            //instance = new SubjectModelApiGet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubjectModelApiGet
        /// </summary>
        [Fact]
        public void SubjectModelApiGetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubjectModelApiGet
            //Assert.IsInstanceOfType<SubjectModelApiGet> (instance, "variable 'instance' is a SubjectModelApiGet");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
