/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetInfoSchema
    /// </summary>
    [DataContract]
    public partial class GetInfoSchema :  IEquatable<GetInfoSchema>, IValidatableObject
    {
        /// <summary>
        /// Defines Keys
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KeysEnum
        {
            /// <summary>
            /// Enum Addcolumns for value: add_columns
            /// </summary>
            [EnumMember(Value = "add_columns")]
            Addcolumns = 1,

            /// <summary>
            /// Enum Editcolumns for value: edit_columns
            /// </summary>
            [EnumMember(Value = "edit_columns")]
            Editcolumns = 2,

            /// <summary>
            /// Enum Filters for value: filters
            /// </summary>
            [EnumMember(Value = "filters")]
            Filters = 3,

            /// <summary>
            /// Enum Permissions for value: permissions
            /// </summary>
            [EnumMember(Value = "permissions")]
            Permissions = 4,

            /// <summary>
            /// Enum Addtitle for value: add_title
            /// </summary>
            [EnumMember(Value = "add_title")]
            Addtitle = 5,

            /// <summary>
            /// Enum Edittitle for value: edit_title
            /// </summary>
            [EnumMember(Value = "edit_title")]
            Edittitle = 6,

            /// <summary>
            /// Enum None for value: none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 7

        }


        /// <summary>
        /// Gets or Sets Keys
        /// </summary>
        [DataMember(Name="keys", EmitDefaultValue=false)]
        public List<KeysEnum> Keys { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetInfoSchema" /> class.
        /// </summary>
        /// <param name="addColumns">addColumns.</param>
        /// <param name="keys">keys.</param>
        public GetInfoSchema(Dictionary<string, GetInfoSchemaAddColumns> addColumns = default(Dictionary<string, GetInfoSchemaAddColumns>), List<KeysEnum> keys = default(List<KeysEnum>))
        {
            this.AddColumns = addColumns;
            this.Keys = keys;
        }
        
        /// <summary>
        /// Gets or Sets AddColumns
        /// </summary>
        [DataMember(Name="add_columns", EmitDefaultValue=false)]
        public Dictionary<string, GetInfoSchemaAddColumns> AddColumns { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetInfoSchema {\n");
            sb.Append("  AddColumns: ").Append(AddColumns).Append("\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetInfoSchema);
        }

        /// <summary>
        /// Returns true if GetInfoSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of GetInfoSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetInfoSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AddColumns == input.AddColumns ||
                    this.AddColumns != null &&
                    input.AddColumns != null &&
                    this.AddColumns.SequenceEqual(input.AddColumns)
                ) && 
                (
                    this.Keys == input.Keys ||
                    this.Keys.SequenceEqual(input.Keys)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AddColumns != null)
                    hashCode = hashCode * 59 + this.AddColumns.GetHashCode();
                hashCode = hashCode * 59 + this.Keys.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
