/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetListSchema
    /// </summary>
    [DataContract]
    public partial class GetListSchema :  IEquatable<GetListSchema>, IValidatableObject
    {
        /// <summary>
        /// Defines Keys
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KeysEnum
        {
            /// <summary>
            /// Enum Listcolumns for value: list_columns
            /// </summary>
            [EnumMember(Value = "list_columns")]
            Listcolumns = 1,

            /// <summary>
            /// Enum Ordercolumns for value: order_columns
            /// </summary>
            [EnumMember(Value = "order_columns")]
            Ordercolumns = 2,

            /// <summary>
            /// Enum Labelcolumns for value: label_columns
            /// </summary>
            [EnumMember(Value = "label_columns")]
            Labelcolumns = 3,

            /// <summary>
            /// Enum Descriptioncolumns for value: description_columns
            /// </summary>
            [EnumMember(Value = "description_columns")]
            Descriptioncolumns = 4,

            /// <summary>
            /// Enum Listtitle for value: list_title
            /// </summary>
            [EnumMember(Value = "list_title")]
            Listtitle = 5,

            /// <summary>
            /// Enum None for value: none
            /// </summary>
            [EnumMember(Value = "none")]
            None = 6

        }


        /// <summary>
        /// Gets or Sets Keys
        /// </summary>
        [DataMember(Name="keys", EmitDefaultValue=false)]
        public List<KeysEnum> Keys { get; set; }
        /// <summary>
        /// Defines OrderDirection
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OrderDirectionEnum
        {
            /// <summary>
            /// Enum Asc for value: asc
            /// </summary>
            [EnumMember(Value = "asc")]
            Asc = 1,

            /// <summary>
            /// Enum Desc for value: desc
            /// </summary>
            [EnumMember(Value = "desc")]
            Desc = 2

        }

        /// <summary>
        /// Gets or Sets OrderDirection
        /// </summary>
        [DataMember(Name="order_direction", EmitDefaultValue=false)]
        public OrderDirectionEnum? OrderDirection { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetListSchema" /> class.
        /// </summary>
        /// <param name="columns">columns.</param>
        /// <param name="filters">filters.</param>
        /// <param name="keys">keys.</param>
        /// <param name="orderColumn">orderColumn.</param>
        /// <param name="orderDirection">orderDirection.</param>
        /// <param name="page">page.</param>
        /// <param name="pageSize">pageSize.</param>
        public GetListSchema(List<string> columns = default(List<string>), List<GetListSchemaFilters> filters = default(List<GetListSchemaFilters>), List<KeysEnum> keys = default(List<KeysEnum>), string orderColumn = default(string), OrderDirectionEnum? orderDirection = default(OrderDirectionEnum?), int page = default(int), int pageSize = default(int))
        {
            this.Columns = columns;
            this.Filters = filters;
            this.Keys = keys;
            this.OrderColumn = orderColumn;
            this.OrderDirection = orderDirection;
            this.Page = page;
            this.PageSize = pageSize;
        }
        
        /// <summary>
        /// Gets or Sets Columns
        /// </summary>
        [DataMember(Name="columns", EmitDefaultValue=false)]
        public List<string> Columns { get; set; }

        /// <summary>
        /// Gets or Sets Filters
        /// </summary>
        [DataMember(Name="filters", EmitDefaultValue=false)]
        public List<GetListSchemaFilters> Filters { get; set; }

        /// <summary>
        /// Gets or Sets OrderColumn
        /// </summary>
        [DataMember(Name="order_column", EmitDefaultValue=false)]
        public string OrderColumn { get; set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name="page", EmitDefaultValue=false)]
        public int Page { get; set; }

        /// <summary>
        /// Gets or Sets PageSize
        /// </summary>
        [DataMember(Name="page_size", EmitDefaultValue=false)]
        public int PageSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetListSchema {\n");
            sb.Append("  Columns: ").Append(Columns).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("  Keys: ").Append(Keys).Append("\n");
            sb.Append("  OrderColumn: ").Append(OrderColumn).Append("\n");
            sb.Append("  OrderDirection: ").Append(OrderDirection).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PageSize: ").Append(PageSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetListSchema);
        }

        /// <summary>
        /// Returns true if GetListSchema instances are equal
        /// </summary>
        /// <param name="input">Instance of GetListSchema to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetListSchema input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Columns == input.Columns ||
                    this.Columns != null &&
                    input.Columns != null &&
                    this.Columns.SequenceEqual(input.Columns)
                ) && 
                (
                    this.Filters == input.Filters ||
                    this.Filters != null &&
                    input.Filters != null &&
                    this.Filters.SequenceEqual(input.Filters)
                ) && 
                (
                    this.Keys == input.Keys ||
                    this.Keys.SequenceEqual(input.Keys)
                ) && 
                (
                    this.OrderColumn == input.OrderColumn ||
                    (this.OrderColumn != null &&
                    this.OrderColumn.Equals(input.OrderColumn))
                ) && 
                (
                    this.OrderDirection == input.OrderDirection ||
                    this.OrderDirection.Equals(input.OrderDirection)
                ) && 
                (
                    this.Page == input.Page ||
                    this.Page.Equals(input.Page)
                ) && 
                (
                    this.PageSize == input.PageSize ||
                    this.PageSize.Equals(input.PageSize)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Columns != null)
                    hashCode = hashCode * 59 + this.Columns.GetHashCode();
                if (this.Filters != null)
                    hashCode = hashCode * 59 + this.Filters.GetHashCode();
                hashCode = hashCode * 59 + this.Keys.GetHashCode();
                if (this.OrderColumn != null)
                    hashCode = hashCode * 59 + this.OrderColumn.GetHashCode();
                hashCode = hashCode * 59 + this.OrderDirection.GetHashCode();
                hashCode = hashCode * 59 + this.Page.GetHashCode();
                hashCode = hashCode * 59 + this.PageSize.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
