/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SubjectInfoModelApiPut
    /// </summary>
    [DataContract]
    public partial class SubjectInfoModelApiPut :  IEquatable<SubjectInfoModelApiPut>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubjectInfoModelApiPut" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubjectInfoModelApiPut() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubjectInfoModelApiPut" /> class.
        /// </summary>
        /// <param name="info">info (required).</param>
        public SubjectInfoModelApiPut(string info = default(string))
        {
            // to ensure "info" is required (not null)
            if (info == null)
            {
                throw new InvalidDataException("info is a required property for SubjectInfoModelApiPut and cannot be null");
            }
            else
            {
                this.Info = info;
            }

        }
        
        /// <summary>
        /// Gets or Sets Info
        /// </summary>
        [DataMember(Name="info", EmitDefaultValue=false)]
        public string Info { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubjectInfoModelApiPut {\n");
            sb.Append("  Info: ").Append(Info).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubjectInfoModelApiPut);
        }

        /// <summary>
        /// Returns true if SubjectInfoModelApiPut instances are equal
        /// </summary>
        /// <param name="input">Instance of SubjectInfoModelApiPut to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubjectInfoModelApiPut input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Info == input.Info ||
                    (this.Info != null &&
                    this.Info.Equals(input.Info))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Info != null)
                    hashCode = hashCode * 59 + this.Info.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
