/* 
 * Femr Core
 *
 * Femr Core
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OpenApiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OpenApiApiTests : IDisposable
    {
        private OpenApiApi instance;

        public OpenApiApiTests()
        {
            instance = new OpenApiApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenApiApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' OpenApiApi
            //Assert.IsType(typeof(OpenApiApi), instance, "instance is a OpenApiApi");
        }

        
        /// <summary>
        /// Test OpenapiVersionOpenapiGet
        /// </summary>
        [Fact]
        public void OpenapiVersionOpenapiGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string version = null;
            //var response = instance.OpenapiVersionOpenapiGet(version);
            //Assert.IsType<Object> (response, "response is Object");
        }
        
    }

}
