#See the postgres Docker Documentation here:
#https://hub.docker.com/_/postgres

#
version: '3.7'

services:
  db:
    container_name: dbServiceFemrDb
    #image:version
    image: postgres:12
    environment:
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=admin"
      - "POSTGRES_DB=test"
      - "PGDATA=/var/lib/postgresql/data"
    ports:
      #Outside:Inside
      - "5432:5432"
    volumes:
      #Need this to persist data
      #Outside:Inside
      - ../dockerVolumes/dbServiceFemrDb:/var/lib/postgresql/data
    networks:
      - femrNetDb

networks:
  femrNetDb: