#Nothing needed to build, we are just using the PostgreSQL image.
#Not using SQLite, because its a file, and we can't easily access it
#through a port, and not MySQL because PostgreSQL is licensed under the
#MIT license, whereas MySQL is GNU/GPLv3, and this at some point
#May be used in a for-profit software